AllCops:
  Exclude:
    - 'spec/support/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false
