language: ruby
sudo: false
cache: bundler
rvm:
  - '2.2'
  - '2.1'
  - '2.0'
  - ruby-head
  - rbx-2
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
