language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.1
  - 2.4.4
  - 2.4.1
  - 2.3.7
  - 2.2
  - 2.1
  - 2.0
  - ruby-head
  - jruby-1.7.26
  - jruby-head
env:
  global:
    - JRUBY_OPTS="--2.0"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install:
  - gem update --system
  - gem install bundler -v 1.16.2
